"""Rendering of a :class:`~fp30x_studio.performance.Performance`.

The one figure here shows the three views of the same object stacked on a
shared time axis:

1. the support -- every strike as a closed interval on its own key, shaded by
   momentum ``P``;
2. the polyphony ``n(t) = sum_k sum_i 1_{I_{k,i}}(t)``;
3. the cumulative energy ``F(t) = int_{-inf}^t sum_k f_k``, normalised by the
   actuator total ``F(T)``, for both the actuator and the CC64 sounding
   representations.

The demo input is generated by :func:`cantor_phrase`, which places notes on the
surviving intervals of a middle-thirds construction so that ``F`` is forced
into the devil's-staircase silhouette Jake expects: flat on the removed thirds,
rising on the survivors, with the self-similar gap structure visible in the
plateau widths.  ``F`` here is absolutely continuous -- the exceptional set has
positive measure -- so it is a *Cantor-function approximant*, not the Cantor
function; the resemblance is in the shape, and it improves as the construction
depth grows and the note durations shrink.

Run ``python -m fp30x_studio.figures`` to write the PNG.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from .performance import Performance, midi_note, synthesize_midi

# -- palette (validated: node scripts/validate_palette.js "#2a78d6,#eb6834,#1baf7a"
#    --mode light --pairs all -> all checks pass; aqua sits below 3:1 on the light
#    surface, so the relief rule applies and every series is direct-labelled) ----
SURFACE = "#fcfcfb"
PAGE = "#f9f9f7"
INK = "#0b0b0b"
INK_2 = "#52514e"
MUTED = "#898781"
GRID = "#e1e0d9"
AXIS = "#c3c2b7"
SERIES_1 = "#2a78d6"  # blue
SERIES_2 = "#eb6834"  # orange
SERIES_3 = "#1baf7a"  # aqua
# sequential blue ramp, light -> dark, for the velocity magnitude encoding
BLUE_RAMP = ["#cde2fb", "#9ec5f4", "#6da7ec", "#3987e5", "#256abf", "#184f95",
             "#0d366b"]


def cantor_phrase(depth: int = 4, span: float = 24.0, base: int = 48
                  ) -> tuple[list[tuple[int, float, float, int]],
                             list[tuple[float, float]]]:
    """Notes placed on the surviving intervals of a middle-thirds construction.

    At depth ``d`` the construction leaves ``2^d`` closed intervals of length
    ``span / 3^d``; a three-note chord is voiced on each one.  The binary
    address of an interval (0 for each left third taken, 1 for each right)
    picks the pitch, so the self-similarity of the Cantor set shows up as
    self-similarity in the voicing as well as in the plateau widths.

    Velocities are a deterministic function of the address, not random, so the
    figure is byte-reproducible.  Returns ``(notes, pedal)`` in the tuple form
    :func:`~fp30x_studio.performance.synthesize_midi` accepts.
    """
    intervals: list[tuple[float, float, tuple[int, ...]]] = [(0.0, span, ())]
    for _ in range(depth):
        nxt = []
        for a, b, addr in intervals:
            third = (b - a) / 3.0
            nxt.append((a, a + third, addr + (0,)))
            nxt.append((b - third, b, addr + (1,)))
        intervals = nxt

    notes: list[tuple[int, float, float, int]] = []
    for a, b, addr in intervals:
        code = sum(bit << i for i, bit in enumerate(reversed(addr)))
        root = base + [0, 3, 5, 7, 10, 12, 15, 17][code % 8] + 12 * (code % 3)
        width = b - a
        for j, interval in enumerate((0, 4, 7)):
            vel = 62 + 8 * ((code + j) % 6) + 5 * j
            notes.append((root + interval,
                          a + 0.04 * width * j,
                          b - 0.02 * width * j,
                          min(127, vel)))
    # pedal held across one second-level block, so its effect on F is local
    # and the staircase either side of it stays legible
    pedal = [(span * 2.0 / 9.0 - 0.15, span / 3.0 + 0.30)]
    return notes, pedal


def demo_performance(**kwargs) -> Performance:
    """Parse the synthetic Cantor phrase through the real MIDI path.

    Deliberately routed through :func:`synthesize_midi` and
    :meth:`Performance.from_messages` rather than constructed directly, so the
    figure exercises the same parser a live capture would.
    """
    notes, pedal = cantor_phrase(**kwargs)
    mid = synthesize_midi(notes, pedal, ticks_per_beat=960, bpm=120.0)
    t = 0.0
    msgs = []
    for msg in mid:
        t += msg.time
        if not msg.is_meta:
            msgs.append((t, msg))
    return Performance.from_messages(msgs)


def _style():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    plt.rcParams.update({
        "figure.facecolor": PAGE,
        "axes.facecolor": SURFACE,
        "savefig.facecolor": PAGE,
        "font.family": "sans-serif",
        "font.sans-serif": ["Helvetica Neue", "Helvetica", "Arial", "DejaVu Sans"],
        "text.color": INK,
        "axes.edgecolor": AXIS,
        "axes.labelcolor": INK_2,
        "xtick.color": MUTED,
        "ytick.color": MUTED,
        "xtick.labelsize": 9,
        "ytick.labelsize": 9,
        "axes.labelsize": 10,
        "axes.linewidth": 0.8,
        "grid.color": GRID,
        "grid.linewidth": 0.6,
        "legend.frameon": False,
        "legend.fontsize": 9,
    })
    return plt


def render(path: str | Path, perf: Performance | None = None, dpi: int = 200) -> Path:
    """Write the three-panel figure to ``path`` and return it."""
    plt = _style()
    from matplotlib.colors import LinearSegmentedColormap, Normalize
    from matplotlib.cm import ScalarMappable

    p = perf if perf is not None else demo_performance()
    sounding = p.with_sustain()
    strikes = p.strikes()
    t0, t1 = p.t_start, max(p.t_end, sounding.t_end)

    fig, (ax0, ax1, ax2) = plt.subplots(
        3, 1, figsize=(11.5, 9.0), sharex=True,
        gridspec_kw={"height_ratios": [2.6, 1.0, 2.4], "hspace": 0.30})
    fig.subplots_adjust(left=0.075, right=0.905, top=0.855, bottom=0.075)

    cmap = LinearSegmentedColormap.from_list("velocity", BLUE_RAMP)
    vels = np.array([s.velocity for s in strikes])
    norm = Normalize(vmin=float(vels.min()), vmax=float(vels.max()))

    # -- panel 1: the support, key by key ---------------------------------
    for a, b in p.pedal:
        ax0.axvspan(a, b, color=SERIES_2, alpha=0.10, lw=0, zorder=0)
        ax0.annotate("sustain pedal down", ((a + b) / 2, 0.985),
                     xycoords=("data", "axes fraction"), ha="center", va="top",
                     fontsize=8.5, color=SERIES_2, zorder=4)
    for s in strikes:
        ax0.plot([s.t_on, s.t_off], [s.key, s.key],
                 color=cmap(norm(s.velocity)), lw=4.0,
                 solid_capstyle="round", zorder=2)
    keys = p.active_keys()
    ax0.set_ylim(min(keys) - 3, max(keys) + 3)
    ticks = [k for k in keys if midi_note(k) % 12 == 0]
    ax0.set_yticks(ticks)
    ax0.set_yticklabels([f"C{midi_note(k) // 12 - 1}" for k in ticks])
    ax0.set_ylabel("key")
    ax0.set_title(
        "Support: every strike as a closed interval $[T_1, T_2]$ on its own key",
        loc="left", fontsize=11, color=INK, pad=8)

    # the colour key sits in its own figure-level axes so that all three
    # panels keep exactly the same width and the shared time axis lines up
    box = ax0.get_position()
    cax = fig.add_axes([box.x1 + 0.014, box.y0, 0.011, box.height])
    cb = fig.colorbar(ScalarMappable(norm=norm, cmap=cmap), cax=cax)
    cb.set_label("momentum $P$", color=INK_2, fontsize=9)
    cb.outline.set_visible(False)
    cb.ax.tick_params(color=MUTED, labelcolor=MUTED, labelsize=8, length=3)

    # -- panel 2: polyphony ------------------------------------------------
    ts, counts = p.polyphony_steps()
    ax1.step(np.append(ts, t1), np.append(counts, counts[-1]), where="post",
             color=INK_2, lw=1.4, zorder=3)
    ax1.fill_between(np.append(ts, t1), np.append(counts, counts[-1]), step="post",
                     color=INK_2, alpha=0.10, lw=0, zorder=1)
    ax1.set_ylabel("$n(t)$")
    ax1.set_ylim(0, p.max_polyphony() + 1)
    ax1.set_title("Polyphony $n(t)=\\sum_k\\sum_i \\mathbf{1}_{I_{k,i}}(t)$ — "
                  f"peak {p.max_polyphony()}",
                  loc="left", fontsize=11, color=INK, pad=8)

    # -- panel 3: cumulative energy ---------------------------------------
    # each curve is indexed to its own total, so the two sit on one axis and
    # the comparison is of shape; the absolute totals are in the labels
    for j, (a, b) in enumerate(p.plateaus()):
        ax2.axvspan(a, b, color=GRID, alpha=0.6, lw=0, zorder=0,
                    label="plateau of the actuator $F$ ($f\\equiv 0$)"
                          if j == 0 else None)
    grid = np.linspace(t0, t1, 1200)
    traces = []
    for src, colour, label in ((p, SERIES_1, "actuator"),
                               (sounding, SERIES_2, "sounding (CC64 applied)")):
        cts, cfs = src.cumulative_curve()
        cts, cfs = np.append(cts, t1), np.append(cfs, cfs[-1])
        y = cfs / cfs[-1]
        ax2.plot(cts, y, color=colour, lw=2.0, zorder=3,
                 solid_capstyle="round",
                 label=f"{label} — $F(T)$ = {cfs[-1]:,.0f} velocity·s")
        traces.append((np.interp(grid, cts, y), colour, label))

    # direct labels at the instant the two representations differ most
    sep = np.abs(traces[0][0] - traces[1][0])
    j = int(np.argmax(sep))
    for y, colour, label in traces:
        above = y[j] >= traces[0][0][j] and y[j] >= traces[1][0][j]
        ax2.annotate(label, (grid[j], y[j]), xytext=(6, 9 if above else -14),
                     textcoords="offset points", color=colour, fontsize=9,
                     zorder=4)

    ax2.legend(loc="upper left", labelcolor=INK_2)
    ax2.set_ylabel("$F(t)\\,/\\,F(T)$")
    ax2.set_xlabel("time $t$ (s)")
    ax2.set_ylim(-0.04, 1.22)
    ax2.set_title("Cumulative energy $F(t)=\\int_{-\\infty}^{t} "
                  "\\sum_k f_k(s)\\,ds$ — monotone, flat off the support",
                  loc="left", fontsize=11, color=INK, pad=8)

    for ax in (ax0, ax1, ax2):
        ax.set_xlim(t0, t1)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.spines["left"].set_color(AXIS)
        ax.spines["bottom"].set_color(AXIS)
        ax.grid(axis="x", zorder=0)
        ax.set_axisbelow(True)
    ax2.grid(axis="y", zorder=0)

    fig.suptitle("A performance as an $\\mathbb{R}^{88}$-valued step function",
                 x=0.055, y=0.975, ha="left", fontsize=16, color=INK,
                 fontweight="bold")
    fig.text(0.055, 0.933,
             "$f=\\bigoplus_{k}\\sum_i P_i\\,\\mathbf{1}_{[T_1^i,\\,T_2^i]}$   "
             "synthetic input: chords on the surviving intervals of a "
             "depth-4 middle-thirds construction",
             ha="left", va="top", fontsize=10.5, color=INK_2)
    fig.text(0.055, 0.012,
             f"{p.n_strikes} strikes on {len(keys)} keys · support "
             f"{p.support_measure():.2f} s of {t1 - t0:.2f} s · "
             f"{len(p.plateaus())} plateaus · total variation "
             f"$V_{{\\ell^1}}(f)={p.total_variation('l1'):.0f}$ · "
             f"generated by fp30x_studio.figures, no live keyboard input",
             ha="left", fontsize=8.5, color=MUTED)

    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=dpi)
    plt.close(fig)
    return out


DEFAULT_OUTPUT = Path(__file__).resolve().parent.parent / "docs" / "cumulative-energy.png"


def main() -> None:
    p = demo_performance()
    print(p.summary())
    out = render(DEFAULT_OUTPUT, p)
    print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
